:man_technologist: Changes in LoRaMAC.cpp Class C AU 915
ElectronicCats/Beelan-LoRaWAN pull request #132
Opened 2022-07-21 18:19 UTC by aleamar264

Fix Class C AU 915

2022-08-01 14:25 UTC, sabas1080 approved these changes

2022-08-05 17:24 UTC, wero1414 requested changes
Need to clean the defines on the file LoRaMAC.cpp the subband config seems good

2022-08-05 17:24 UTC, wero1414 commented on src/arduino-rfm/LoRaMAC.cpp
> +#define AU_915 // use the band youy need
The library specifies that this needs to be defined on the file Config.h not in the LoRaMAC.cpp

2022-08-05 17:24 UTC, wero1414 commented on src/arduino-rfm/LoRaMAC.cpp
> +#define SUBND_0 // same here!
This should be defined con the config.h too

2022-09-22 18:33 UTC, sabas1080 commented
Now available in #138

2022-09-22 18:33 UTC, closed without merging