Temp fix for issue #197 Downlink no longer works - esp32
ElectronicCats/Beelan-LoRaWAN pull request #198
Opened 2024-06-25 23:01 UTC by REGIOIGER

2024-06-25 23:03 UTC, sabas1080 approved these changes

2024-06-25 23:15 UTC, sabas1080 requested changes
Porque dejar los comentarios?

2024-08-02 18:43 UTC, REGIOIGER commented on src/arduino-rfm/lorawan-arduino-rfm.cpp
> +    LoRa_Settings.Rx2_Delay = 6000; // Rx2_Delay >= Rx1_Delay + RX1_Window
Listo

2024-08-02 19:05 UTC, sabas1080 approved these changes

2024-08-02 19:05 UTC, merged